/**
 * attraction api reponse format
 */
export default interface IAttraction {
    "id": number,
    "Id": string,
    "Name": string,
    "Zone": string,
    "Toldescribe": string,
    "Description": string,
    "Tel": string,
    "Add": string,
    "Zipcode": string,
    "Region": string,
    "Town": string,
    "Travellinginfo": string,
    "Opentime": string,
    "Picture1": string,
    "Picdescribe1": string,
    "Picture2": string,
    "Picdescribe2": string,
    "Picture3": string,
    "Picdescribe3": string,
    "Map": string,
    "Gov": string,
    "Px": number,
    "Py": number,
    "Orgclass": string,
    "Class1": string,
    "Class2": string,
    "Class3": string,
    "Level": string,
    "Website": string,
    "Parkinginfo": string,
    "Parkinginfo_Px": number | null,
    "Parkinginfo_Py": number | null,
    "Ticketinfo": string,
    "Remarks": string,
    "Keyword": string,
    "Changetime": string
}